package ahorcado.interfaz;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Alejandro González Navarro
 */
public class Interfaz extends javax.swing.JFrame {
    private Image img = Toolkit.getDefaultToolkit().getImage("ahorcado_titulo.jpg");
    /**
     * Creates new form Interfaz
     */
    
    public Interfaz() {
        initComponents();
        // Configuración que no funciona en el constructor
        this.getContentPane().setBackground(Color.white);           // Color de fondo
        this.setLocationRelativeTo(null);                           // Posicionamiento en el centro
        this.setIconImage(new ImageIcon("src/main/resources/ahorcado/imagen/icono.png").getImage());    // Logo en miniatura        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonComenzar = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(852, 752));
        setResizable(false);
        setSize(new java.awt.Dimension(852, 752));
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Viner Hand ITC", 0, 100)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("ElAhorcado");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(0, 10, 830, 162);

        jButtonComenzar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonComenzar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButtonComenzar.setForeground(new java.awt.Color(0, 0, 255));
        jButtonComenzar.setText("Comenzar");
        jButtonComenzar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButtonComenzar.setBorderPainted(false);
        jButtonComenzar.setFocusPainted(false);
        jButtonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComenzar);
        jButtonComenzar.setBounds(200, 610, 430, 70);

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/imagen/ahorcado_titulo.jpg"))); // NOI18N
        getContentPane().add(jLabelImagen);
        jLabelImagen.setBounds(0, 0, 836, 713);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarActionPerformed
        juego Juego = new juego(this,true);
        Juego.setVisible(true);
    }//GEN-LAST:event_jButtonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComenzar;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
