package ahorcado.interfaz;

import ahorcado.logica.logica;
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author Alejandro González Navarro
 */
public class juego extends javax.swing.JDialog {
    /**
     * Creates new form NewJDialog
     */
    private logica Logica;
    public juego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Configuración que no funciona en el constructor
        jLabelFraseDePista.setVisible(false);
        Logica = new logica(jLabelPalabra);                         // Inicializar logica

        this.getContentPane().setBackground(new java.awt.Color(230, 250, 228));           // Color de fondo
        this.setLocationRelativeTo(null);                           // Posicionamiento en el centro
        this.setIconImage(new ImageIcon("src/main/resources/ahorcado/imagen/icono.png").getImage());    // Logo en miniatura
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPalabra = new javax.swing.JLabel();
        jButtonPista = new javax.swing.JButton();
        jPanelTeclado = new javax.swing.JPanel();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonÑ = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelBotonesFinales = new javax.swing.JPanel();
        jButtonVolverAlInicio = new javax.swing.JButton();
        jButtonJugarDeNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelFraseDePista = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ahorcado");
        setIconImage(null);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(851, 752));
        setMinimumSize(new java.awt.Dimension(851, 752));
        setResizable(false);
        setSize(new java.awt.Dimension(851, 752));
        getContentPane().setLayout(null);

        jLabelPalabra.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabelPalabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPalabra.setText("_ _ _ _ _ _ _");
        getContentPane().add(jLabelPalabra);
        jLabelPalabra.setBounds(270, 310, 320, 37);

        jButtonPista.setBackground(new java.awt.Color(255, 255, 153));
        jButtonPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/imagen/hint.png"))); // NOI18N
        jButtonPista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonPista.setBorderPainted(false);
        jButtonPista.setFocusPainted(false);
        jButtonPista.setPreferredSize(new java.awt.Dimension(45, 45));
        jButtonPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPistaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPista);
        jButtonPista.setBounds(670, 370, 45, 45);

        jPanelTeclado.setBackground(new java.awt.Color(168, 172, 175));
        jPanelTeclado.setLayout(null);

        jButtonA.setText("A");
        jButtonA.setBackground(new java.awt.Color(255, 255, 204));
        jButtonA.setForeground(new java.awt.Color(0, 0, 255));
        jButtonA.setMnemonic('a');
        jButtonA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonA.setBorderPainted(false);
        jButtonA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonA.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonA);
        jButtonA.setBounds(190, 10, 35, 38);

        jButtonB.setBackground(new java.awt.Color(255, 255, 204));
        jButtonB.setForeground(new java.awt.Color(0, 0, 255));
        jButtonB.setText("B");
        jButtonB.setMnemonic('b');
        jButtonB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonB.setBorderPainted(false);
        jButtonB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonB.setFocusPainted(false);
        jButtonB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonB.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonB.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonB);
        jButtonB.setBounds(240, 10, 35, 38);

        jButtonC.setBackground(new java.awt.Color(255, 255, 204));
        jButtonC.setForeground(new java.awt.Color(0, 0, 255));
        jButtonC.setText("C");
        jButtonC.setMnemonic('c');
        jButtonC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonC.setBorderPainted(false);
        jButtonC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonC.setFocusPainted(false);
        jButtonC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonC.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonC.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonC.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonC);
        jButtonC.setBounds(290, 10, 35, 38);

        jButtonD.setBackground(new java.awt.Color(255, 255, 204));
        jButtonD.setForeground(new java.awt.Color(0, 0, 255));
        jButtonD.setText("D");
        jButtonD.setMnemonic('d');
        jButtonD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonD.setBorderPainted(false);
        jButtonD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonD.setFocusPainted(false);
        jButtonD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonD.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonD.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonD.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonD);
        jButtonD.setBounds(340, 10, 35, 38);

        jButtonE.setBackground(new java.awt.Color(255, 255, 204));
        jButtonE.setForeground(new java.awt.Color(0, 0, 255));
        jButtonE.setText("E");
        jButtonE.setMnemonic('e');
        jButtonE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonE.setBorderPainted(false);
        jButtonE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonE.setFocusPainted(false);
        jButtonE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonE.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonE.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonE.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonE);
        jButtonE.setBounds(390, 10, 35, 38);

        jButtonF.setBackground(new java.awt.Color(255, 255, 204));
        jButtonF.setForeground(new java.awt.Color(0, 0, 255));
        jButtonF.setText("F");
        jButtonF.setMnemonic('f');
        jButtonF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonF.setBorderPainted(false);
        jButtonF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonF.setFocusPainted(false);
        jButtonF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonF.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonF.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonF.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonF);
        jButtonF.setBounds(440, 10, 35, 38);

        jButtonG.setBackground(new java.awt.Color(255, 255, 204));
        jButtonG.setForeground(new java.awt.Color(0, 0, 255));
        jButtonG.setText("G");
        jButtonG.setMnemonic('g');
        jButtonG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonG.setBorderPainted(false);
        jButtonG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonG.setFocusPainted(false);
        jButtonG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonG.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonG.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonG.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonG);
        jButtonG.setBounds(490, 10, 35, 38);

        jButtonH.setBackground(new java.awt.Color(255, 255, 204));
        jButtonH.setForeground(new java.awt.Color(0, 0, 255));
        jButtonH.setText("H");
        jButtonH.setMnemonic('h');
        jButtonH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonH.setBorderPainted(false);
        jButtonH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonH.setFocusPainted(false);
        jButtonH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonH.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonH.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonH.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonH);
        jButtonH.setBounds(540, 10, 35, 38);

        jButtonI.setBackground(new java.awt.Color(255, 255, 204));
        jButtonI.setForeground(new java.awt.Color(0, 0, 255));
        jButtonI.setText("I");
        jButtonI.setMnemonic('i');
        jButtonI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonI.setBorderPainted(false);
        jButtonI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonI.setFocusPainted(false);
        jButtonI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonI.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonI.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonI.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonI);
        jButtonI.setBounds(590, 10, 35, 38);

        jButtonJ.setBackground(new java.awt.Color(255, 255, 204));
        jButtonJ.setForeground(new java.awt.Color(0, 0, 255));
        jButtonJ.setText("J");
        jButtonJ.setMnemonic('j');
        jButtonJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonJ.setBorderPainted(false);
        jButtonJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJ.setFocusPainted(false);
        jButtonJ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonJ.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonJ.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonJ.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonJ);
        jButtonJ.setBounds(190, 60, 35, 38);

        jButtonK.setBackground(new java.awt.Color(255, 255, 204));
        jButtonK.setForeground(new java.awt.Color(0, 0, 255));
        jButtonK.setText("K");
        jButtonK.setMnemonic('k');
        jButtonK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonK.setBorderPainted(false);
        jButtonK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonK.setFocusPainted(false);
        jButtonK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonK.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonK.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonK.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonK);
        jButtonK.setBounds(240, 60, 35, 38);

        jButtonL.setBackground(new java.awt.Color(255, 255, 204));
        jButtonL.setForeground(new java.awt.Color(0, 0, 255));
        jButtonL.setText("L");
        jButtonL.setMnemonic('l');
        jButtonL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL.setBorderPainted(false);
        jButtonL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonL.setFocusPainted(false);
        jButtonL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonL.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonL.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonL.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonL);
        jButtonL.setBounds(290, 60, 35, 38);

        jButtonM.setBackground(new java.awt.Color(255, 255, 204));
        jButtonM.setForeground(new java.awt.Color(0, 0, 255));
        jButtonM.setText("M");
        jButtonM.setMnemonic('m');
        jButtonM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonM.setBorderPainted(false);
        jButtonM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonM.setFocusPainted(false);
        jButtonM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonM.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonM.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonM.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonM);
        jButtonM.setBounds(340, 60, 35, 38);

        jButtonN.setBackground(new java.awt.Color(255, 255, 204));
        jButtonN.setForeground(new java.awt.Color(0, 0, 255));
        jButtonN.setText("N");
        jButtonN.setMnemonic('n');
        jButtonN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonN.setBorderPainted(false);
        jButtonN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonN.setFocusPainted(false);
        jButtonN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonN.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonN.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonN.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonN);
        jButtonN.setBounds(390, 60, 35, 38);

        jButtonÑ.setBackground(new java.awt.Color(255, 255, 204));
        jButtonÑ.setForeground(new java.awt.Color(0, 0, 255));
        jButtonÑ.setText("Ñ");
        jButtonÑ.setMnemonic('\u00f1');
        jButtonÑ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonÑ.setBorderPainted(false);
        jButtonÑ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonÑ.setFocusPainted(false);
        jButtonÑ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonÑ.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonÑ.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonÑ.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonÑActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonÑ);
        jButtonÑ.setBounds(440, 60, 35, 38);

        jButtonO.setBackground(new java.awt.Color(255, 255, 204));
        jButtonO.setForeground(new java.awt.Color(0, 0, 255));
        jButtonO.setText("O");
        jButtonO.setMnemonic('o');
        jButtonO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonO.setBorderPainted(false);
        jButtonO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonO.setFocusPainted(false);
        jButtonO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonO.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonO.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonO.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonO);
        jButtonO.setBounds(490, 60, 35, 38);

        jButtonP.setBackground(new java.awt.Color(255, 255, 204));
        jButtonP.setForeground(new java.awt.Color(0, 0, 255));
        jButtonP.setText("P");
        jButtonP.setMnemonic('p');
        jButtonP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonP.setBorderPainted(false);
        jButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonP.setFocusPainted(false);
        jButtonP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonP.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonP.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonP);
        jButtonP.setBounds(540, 60, 35, 38);

        jButtonQ.setBackground(new java.awt.Color(255, 255, 204));
        jButtonQ.setForeground(new java.awt.Color(0, 0, 255));
        jButtonQ.setText("Q");
        jButtonQ.setMnemonic('q');
        jButtonQ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonQ.setBorderPainted(false);
        jButtonQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonQ.setFocusPainted(false);
        jButtonQ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonQ.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonQ.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonQ.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonQ);
        jButtonQ.setBounds(590, 60, 35, 38);

        jButtonR.setBackground(new java.awt.Color(255, 255, 204));
        jButtonR.setForeground(new java.awt.Color(0, 0, 255));
        jButtonR.setText("R");
        jButtonR.setMnemonic('r');
        jButtonR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonR.setBorderPainted(false);
        jButtonR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonR.setFocusPainted(false);
        jButtonR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonR.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonR.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonR.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonR);
        jButtonR.setBounds(190, 110, 35, 38);

        jButtonS.setBackground(new java.awt.Color(255, 255, 204));
        jButtonS.setForeground(new java.awt.Color(0, 0, 255));
        jButtonS.setText("S");
        jButtonS.setMnemonic('s');
        jButtonS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonS.setBorderPainted(false);
        jButtonS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonS.setFocusPainted(false);
        jButtonS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonS.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonS.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonS.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonS);
        jButtonS.setBounds(240, 110, 35, 38);

        jButtonT.setBackground(new java.awt.Color(255, 255, 204));
        jButtonT.setForeground(new java.awt.Color(0, 0, 255));
        jButtonT.setText("T");
        jButtonT.setMnemonic('t');
        jButtonT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonT.setBorderPainted(false);
        jButtonT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonT.setFocusPainted(false);
        jButtonT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonT.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonT.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonT.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonT);
        jButtonT.setBounds(290, 110, 35, 38);

        jButtonU.setBackground(new java.awt.Color(255, 255, 204));
        jButtonU.setForeground(new java.awt.Color(0, 0, 255));
        jButtonU.setText("U");
        jButtonU.setMnemonic('u');
        jButtonU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonU.setBorderPainted(false);
        jButtonU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonU.setFocusPainted(false);
        jButtonU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonU.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonU.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonU.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonU);
        jButtonU.setBounds(340, 110, 35, 38);

        jButtonV.setBackground(new java.awt.Color(255, 255, 204));
        jButtonV.setForeground(new java.awt.Color(0, 0, 255));
        jButtonV.setText("V");
        jButtonV.setMnemonic('v');
        jButtonV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonV.setBorderPainted(false);
        jButtonV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonV.setFocusPainted(false);
        jButtonV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonV.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonV.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonV);
        jButtonV.setBounds(390, 110, 35, 38);

        jButtonW.setBackground(new java.awt.Color(255, 255, 204));
        jButtonW.setForeground(new java.awt.Color(0, 0, 255));
        jButtonW.setText("W");
        jButtonW.setMnemonic('w');
        jButtonW.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonW.setBorderPainted(false);
        jButtonW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonW.setFocusPainted(false);
        jButtonW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonW.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonW.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonW.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonW);
        jButtonW.setBounds(440, 110, 35, 38);

        jButtonX.setBackground(new java.awt.Color(255, 255, 204));
        jButtonX.setForeground(new java.awt.Color(0, 0, 255));
        jButtonX.setText("X");
        jButtonX.setMnemonic('x');
        jButtonX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonX.setBorderPainted(false);
        jButtonX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonX.setFocusPainted(false);
        jButtonX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonX.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonX.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonX.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonX);
        jButtonX.setBounds(490, 110, 35, 38);

        jButtonY.setBackground(new java.awt.Color(255, 255, 204));
        jButtonY.setForeground(new java.awt.Color(0, 0, 255));
        jButtonY.setText("Y");
        jButtonY.setMnemonic('y');
        jButtonY.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonY.setBorderPainted(false);
        jButtonY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonY.setFocusPainted(false);
        jButtonY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonY.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonY.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonY.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonY);
        jButtonY.setBounds(540, 110, 35, 38);

        jButtonZ.setBackground(new java.awt.Color(255, 255, 204));
        jButtonZ.setForeground(new java.awt.Color(0, 0, 255));
        jButtonZ.setText("Z");
        jButtonZ.setMnemonic('z');
        jButtonZ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonZ.setBorderPainted(false);
        jButtonZ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonZ.setFocusPainted(false);
        jButtonZ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonZ.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonZ.setMaximumSize(new java.awt.Dimension(15, 20));
        jButtonZ.setMinimumSize(new java.awt.Dimension(15, 20));
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });
        jPanelTeclado.add(jButtonZ);
        jButtonZ.setBounds(590, 110, 35, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/imagen/fondoTeclado.png"))); // NOI18N
        jPanelTeclado.add(jLabel1);
        jLabel1.setBounds(1, -10, 890, 190);

        getContentPane().add(jPanelTeclado);
        jPanelTeclado.setBounds(0, 540, 840, 180);

        jPanelBotonesFinales.setBackground(new java.awt.Color(168, 172, 175));
        jPanelBotonesFinales.setLayout(null);

        jButtonVolverAlInicio.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVolverAlInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolverAlInicio.setForeground(new java.awt.Color(0, 0, 255));
        jButtonVolverAlInicio.setText("Volver al inicio");
        jButtonVolverAlInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonVolverAlInicio.setBorderPainted(false);
        jButtonVolverAlInicio.setFocusPainted(false);
        jButtonVolverAlInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAlInicioActionPerformed(evt);
            }
        });
        jPanelBotonesFinales.add(jButtonVolverAlInicio);
        jButtonVolverAlInicio.setBounds(150, 50, 260, 80);

        jButtonJugarDeNuevo.setBackground(new java.awt.Color(255, 255, 204));
        jButtonJugarDeNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonJugarDeNuevo.setForeground(new java.awt.Color(0, 0, 255));
        jButtonJugarDeNuevo.setText("Jugar de nuevo");
        jButtonJugarDeNuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonJugarDeNuevo.setBorderPainted(false);
        jButtonJugarDeNuevo.setFocusPainted(false);
        jButtonJugarDeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarDeNuevoActionPerformed(evt);
            }
        });
        jPanelBotonesFinales.add(jButtonJugarDeNuevo);
        jButtonJugarDeNuevo.setBounds(450, 50, 260, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/imagen/fondoTeclado.png"))); // NOI18N
        jPanelBotonesFinales.add(jLabel2);
        jLabel2.setBounds(1, -3, 890, 170);

        getContentPane().add(jPanelBotonesFinales);
        jPanelBotonesFinales.setBounds(0, 543, 840, 170);
        jPanelBotonesFinales.setVisible(false);

        jLabelFraseDePista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFraseDePista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFraseDePista.setText("Frase de pista");
        getContentPane().add(jLabelFraseDePista);
        jLabelFraseDePista.setBounds(9, 470, 810, 30);

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/imagen/ahocado01.jpg"))); // NOI18N
        jLabelImagen.setAlignmentY(0.0F);
        getContentPane().add(jLabelImagen);
        jLabelImagen.setBounds(0, -10, 850, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Botones">                          
    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        Logica.comprobarLetra(jButtonA,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        Logica.comprobarLetra(jButtonB,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        Logica.comprobarLetra(jButtonC,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        Logica.comprobarLetra(jButtonD,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        Logica.comprobarLetra(jButtonE,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        Logica.comprobarLetra(jButtonF,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
        Logica.comprobarLetra(jButtonG,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonGActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        Logica.comprobarLetra(jButtonH,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonHActionPerformed

    private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
        Logica.comprobarLetra(jButtonI,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonIActionPerformed

    private void jButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJActionPerformed
        Logica.comprobarLetra(jButtonJ,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonJActionPerformed

    private void jButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKActionPerformed
        Logica.comprobarLetra(jButtonK,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonKActionPerformed

    private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
        Logica.comprobarLetra(jButtonL,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonLActionPerformed

    private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed
        Logica.comprobarLetra(jButtonM,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonMActionPerformed

    private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed
        Logica.comprobarLetra(jButtonN,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonNActionPerformed

    private void jButtonÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonÑActionPerformed
        Logica.comprobarLetra(jButtonÑ,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonÑActionPerformed

    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        Logica.comprobarLetra(jButtonO,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonOActionPerformed

    private void jButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPActionPerformed
        Logica.comprobarLetra(jButtonP,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonPActionPerformed

    private void jButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQActionPerformed
        Logica.comprobarLetra(jButtonQ,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonQActionPerformed

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        Logica.comprobarLetra(jButtonR,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSActionPerformed
        Logica.comprobarLetra(jButtonS,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonSActionPerformed

    private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
        Logica.comprobarLetra(jButtonT,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonTActionPerformed

    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
        Logica.comprobarLetra(jButtonU,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonUActionPerformed

    private void jButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVActionPerformed
        Logica.comprobarLetra(jButtonV,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonVActionPerformed

    private void jButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWActionPerformed
        Logica.comprobarLetra(jButtonW,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonWActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        Logica.comprobarLetra(jButtonX,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        Logica.comprobarLetra(jButtonY,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonYActionPerformed

    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        Logica.comprobarLetra(jButtonZ,jLabelPalabra, jLabelImagen, jPanelTeclado, jPanelBotonesFinales,jLabelFraseDePista,jButtonPista);
    }//GEN-LAST:event_jButtonZActionPerformed

    private void jButtonJugarDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarDeNuevoActionPerformed
        Logica.jugarDeNuevo(jLabelPalabra, jPanelTeclado,jLabelImagen, jPanelBotonesFinales, jButtonPista);
    }//GEN-LAST:event_jButtonJugarDeNuevoActionPerformed

    private void jButtonVolverAlInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAlInicioActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAlInicioActionPerformed

    private void jButtonPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPistaActionPerformed
        Logica.getPista(jLabelFraseDePista);
    }//GEN-LAST:event_jButtonPistaActionPerformed
    // </editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                juego dialog = new juego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonJugarDeNuevo;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonPista;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonVolverAlInicio;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JButton jButtonÑ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFraseDePista;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPalabra;
    private javax.swing.JPanel jPanelBotonesFinales;
    private javax.swing.JPanel jPanelTeclado;
    // End of variables declaration//GEN-END:variables
}
